name: Pull Request CI
env:
  CI_BRANCH: ${{ github.head_ref || github.ref_name }}
on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          cache: yarn

      - name: Install Deps
        run:  yarn install --frozen-lockfile

      - name: Git fetch
        run: git fetch --no-tags --prune --depth=1 origin main

      - name: Set branch name as environment variable
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Run Test
        run: npx nx affected:build --base=origin/main --head=$PR_BRANCH_NAME


  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Git fetch
        run: git fetch --no-tags --prune --depth=1 origin main

      - name: Set branch name as environment variable
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Run Test
        run: npx nx affected:lint --base=origin/main --head=$PR_BRANCH_NAME

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Git fetch
        run: git fetch --no-tags --prune --depth=1 origin main

      - name: Set branch name as environment variable
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Run Test
        run: npx nx affected:test --base=origin/main --head=$PR_BRANCH_NAME

