name: Push to Main CI
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      actions: "read"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Run Build
        run: npx nx affected:build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      actions: "read"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Run Eslint
        run: npx nx affected:lint --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}


  test:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      actions: "read"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Run Test
        run: npx nx affected:test --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

  deploy_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      actions: "read"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          cache: yarn

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4


      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run deploy prod
        run: npx nx affected -t deploy:prod --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
